apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "Taskly.fullname" . }}-config
  labels:
    {{- include "Taskly.labels" . | nindent 4 }}
data:
  # Frontend configuration
  NEXT_PUBLIC_BASE_URL: "http://{{ include "Taskly.fullname" . }}-frontend-service:3000"
  NEXT_PUBLIC_API_BASE_URL: "http://{{ include "Taskly.fullname" . }}-backend-service:8000/v1/api"
  NODE_ENV: "production"

  # Backend configuration
  MCP_SERVER_URL: "http://{{ include "Taskly.fullname" . }}-mcp-server-service:8080"
  ENVIRONMENT: "production"
  JWT_ALGORITHM: "EdDSA"

  # MCP Server configuration
  DEBUG: "False"
  PORT: "8080"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  JWT_ALGORITHM_MCP: "HS256"
