apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskflow.fullname" . }}-secrets
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
type: Opaque
data:

# Uncomment these secrets

#   # MCP Server secrets
#   jwt-secret-key: your-jwt-secret-key-here

#   # Backend secrets
#   gemini-api-key: your-gemini-api-key-here

#   # Shared secrets
#   database-url: postgresql://username:password@host:port/database
#   better-auth-secret: your-jwt-secret-key-here

#   # Frontend secrets
#   smtp-user: your-smtp-username-here
#   smtp-pass: your-smtp-password-here
#   chatkit-domain-key: your-chatkit-domain-key-here

  # Database credentials (for PostgreSQL StatefulSet)
  db-user: cG9zdGdyZXM=  # base64 encoded "postgres"
  db-password: cGFzc3dvcmQxMjM=  # base64 encoded "password123"
