apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskflow.fullname" . }}-frontend-service
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "taskflow.selectorLabels" . | nindent 4 }}
