apiVersion: v1
kind: Service
metadata:
  name: {{ include "Taskly.fullname" . }}-mcp-server-service
  labels:
    {{- include "Taskly.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
spec:
  type: {{ .Values.mcpServer.service.type }}
  ports:
    - port: {{ .Values.mcpServer.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "Taskly.selectorLabels" . | nindent 4 }}
