apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskflow.fullname" . }}-backend-service
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "taskflow.selectorLabels" . | nindent 4 }}
