apiVersion: v2
name: taskflow
description: A Helm chart for the Todo Chatbot application with DAPR integration
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - taskflow
  - todo
  - chatbot
  - microservices
  - dapr
  - distributed-systems
  - service-invocation
  - pubsub
  - state-management
